apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: uh62fpr95-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/uh62fpr95-java-quarkus-gitops